version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=cshhacks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  service:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db/cshhacks